### ISSUE TITLE
Build CI/CD pipeline by automating steps for targeted software delivery process

### ISSUE THREAD

**Issue by skarred14** [eea-oasis/baseline#17]
## Overview

As a developer for better release management, and targeted software delivery processes, I would like to leverage a full fledged test suite and infrastructure management framework. Maintenance of build, test, and publish a Baseline utility or application extension can be better managed and handled through a CI/CD pipeline.

### Reference

- [Github Actions](https://github.com/actions)
- [Travis CI](https://github.com/travis-ci/travis-ci)
- [Linting](https://github.com/ethereum-oasis/baseline/issues/16)

### Questions

- Which tool of choice for building Ci/CD pipelines?
- How to consider variability of options for using custom CI/CD tools?

### Acceptance
- Unit tests for `api`, `ui`, `zkp`, `messenger` are updated/created and successfully tun
- Integration tests are updated for queue based management
- Semantic release management is built into the repo
- Automate package builds integrated with github packages

## Tasks

- [ ] Develop test case suite (integration and unit) based on different steps in the workflow
- [ ] Update docker images to Dockerhub to handle concerns around layer caching and compute intensive, high latency tasks
- [ ] Build CI/CD pipeline and associated scripts for semantic release management

**Disclaimer: This is a broad stroke and a sample feature request. It would need to be further updated (potentially broken down into further feature requests), based on discussions with other members of the Oasis community

**Comment by breakpointer** [comment]
e2e test suite requires larger instance sizes than what is available on the free tiers. Looking for CI sponsorships and/or changes to the test suites so individual package test can be run within the instance size limits.

**Comment by ognjenkurtic** [comment]
Closing since it is obsolete. Every reference implementation will setup a separate CI\CD pipeline.
