### ISSUE TITLE
[GR] #42 Tasks List

### ISSUE THREAD

**Issue by Consianimis** [eea-oasis/baseline#382]
## Overview

This issue lists the tasks related to grant [GR] 42 'Baseline Protocol - Project Documentation - Improvement'.
This is a working issue - please do not close.

## Tasks for specifications
- [x] [`CORE`] Editorial review of CORE spec.
- [x] [`CCSM`] Eeditorial review of CCSM spec.
- [ ] [`API`] Editorial review of API spec.

## Tasks for docs.baseline-protocol.org 

- [x] [`Structure`] Review and agree structure with stakeholders.
- [ ] Open-source community
    - [ ] Agree on official communication channels
- [x ] [`Get involved`] 
    - [x] create new 'get involved' section
    - [x] [`for devs`] create sub-section for onboarding devs
        - [x] include list of steps to get involved
        - [x] include list of developer resources:
               - [x] implementation guide
               - [x] codebase
               - [x] bounties
               - [x] dev slack chanel
               - [x] weekly core devs meeting calendar
               - [x] ref implementation/templates/tutorials
    - [x] [`for non-devs`] create sub-section for onboarding non-devs
       - [ ] include list of steps to get involved in outreach team, in standard team, other non dev activities
       - [ ] include list of non-dev resources:
- [x] [`Community`]   
    - [x] SSC to become General Assembly
    - [x] Maintainers to become Core Developers
- [ ] [`Governance`]
   - [x] create new governance section
   - [x ] [`governance`] move existing governance page to new section and rename it more appropriately
     - [x ] [`project governance board`] 
        - [x ] move existing 'community leaders' page to new section and rename it 'project governance board'
   - [x] [`technical steering committee`] move existing tsc page to new section
   - [x] [`specifications steering committee`] 
        - [x] Confirm with Oasis team what happens to standard team once standard is published. 
        - [x] update content of the ssc page
        - [x] move page ssc page to new section
- [x] [`Baseline Protocol Standard`]
    - [x] [`core`] create sub-section for CORE spec
    - [x] [`api`] create sub-section for API spec
    - [x] [`ccsm`] create sub-section for CCSM spec
- [x] [`Baseline Basics`]
   - [x] [`glossary`] update glossary to align with CORE spec draft glossary.
   - [ ] [`glossary`] submit to standard team terminology not included in CORE spec draft but included in doc
   - [x] [`faq`] create faq 
- [x] [`Reference Implementations`]   
   - [x] Update BRI-2 - misalignment between repo and doc.

## Tasks for v.1 roadmap development

- [x] [`documentation`] 
  - [x] [`implementation guide`] request access and review draft
  - [x] [`existing documentation`] request access and review docs from stakeholders
- [ ] [`github repos`] 
  - [ ] [`baseline-roadmap`] review, consolidate, clean 
  - [ ] [`baseline`] review, consolidate, clean 
- [ ] [`roadmap`] 
  - [ ] create template github issue : 'summary, intended outcome, how will it work/how does it work ?, ref to req number'
  - [x] define and agree protocol/feature areas : to be aligned with CORE/API/CCSM specs.
  - [ ] define and agree roadmap stages
  - [ ] create github project for public roadmap
  - [ ] Agree and set up suggested github milestones
      - [ ] v1 Source code completed excl. test suites
      - [ ] v1 Source code test suites completed
      - [ ] v1 Smart contract(s) audit
      - [ ] v1 Standard officially published (CORE, API and CCSM)
      - [ ] v1 Standard test suites completed
      - [ ] v1 Compliant source code released
  - [x] diff between core and https://app.swaggerhub.com/apis-docs/prvd/Baseline-Core/v1.0.0#/
- [ ] [`workshops`] 
  - [x] Wednesday 25th Aug: Daven Jones - Provide, Sam Stokes - Consensys

**Comment by Consianimis** [comment]
This issue can now be closed.
