### ISSUE TITLE
Prepare Workgroup, Workflow and Workstep component proposals as part of the SRI

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#477]
## Overview

Will prepare separate documents for the Workgroup, Workflow, and Workstep components; each outlining the basic functionalities and interfaces needed for the respective component during SRI implementation.

### Acceptance

- Documents created and presented to the team
- Team agrees on each component's set of interfaces and functionalities to be implemented in initial sprint

## Tasks

- [x] Document created
- [x] Document presented to team
- [x] Discussion, possible alteration, and initial acceptance of interfaces and functionalities
- [x] Github issues for implementation stories created

**Comment by Kasshern** [comment]
Accompanying documents are as follows:
1. [Workstep Component](https://docs.google.com/document/d/1jl18QixqTEH30jrdlW0dD-DOydMX1L8lEGCucKv3SXs/edit?usp=sharing)
2. [Workflow Component](https://docs.google.com/document/d/1GRsZrS-OZNU_PEnmzluSChYw85LW0tBlECJwCZcooFk/edit?usp=sharing)
3. [Workgroup Component](https://docs.google.com/document/d/10LWXIBPjzEUrRMfMgeua6_ufiAcmEl6QRRhRLC301Dg/edit?usp=sharing)
