### ISSUE TITLE
Prepare a proposal for the Storage handling component as part of the SRI

### ISSUE THREAD

**Issue by Ybittan** [eea-oasis/baseline#478]
## Overview

Will prepare documents for the Storage components; outlining the basic functionalities and interfaces needed for storage during SRI implementation.

### Acceptance

- Documents created and presented to the team
- Team agrees on each component's set of interfaces and functionalities to be implemented in initial sprint

## Tasks

- [x] Document created
- [x] Document presented to team
- [ ] Discussion, possible alteration, and final acceptance of interfaces and functionalities
- [ ] Github issues for implementation stories created
