### ISSUE TITLE
SRI Storage Component - Database Preparation Tasks

### ISSUE THREAD

**Issue by Ybittan** [eea-oasis/baseline#482]
## Overview

It has been determined that the SRI will need a database. Postgres is the current system of choice. 
This issue will outline the initial tasks necessary to spin up a DB.

### Reference

- [SRI Storage](https://github.com/eea-oasis/baseline/issues/478)

### Acceptance

- Should spin up a database on the machine's local server and connect to it
- Should have a plan for future state of a containerized (Docker) db to spin up fresh

## Tasks

- [x] Create db programmatically
- [x] Use migration library to connect to the DB
- [x] Plan for future Docker components
- [x] Spin up Docker postgres container and connect to it

**Comment by ognjenkurtic** [comment]
Please research tools to enable easy migrations of the db as we introduce new functionalities and models.

**Comment by Ybittan** [comment]
[What data must be stored document](https://docs.google.com/document/d/1RoK9kDxvL4Opg9SSmgdCpgbK88zIJMBJv0umRtR6AZ0/edit?usp=sharing)

**Comment by Ybittan** [comment]
Updated based on suggestions from a comment, reference below:

"I do not think you should and could map all the necessary data at this point.For the purpose of issue https://github.com/eea-oasis/baseline/issues/482, i think it is enough to map the general requirements from the storage layer (as you already did bellow), and then decide on the storage tech itself as well as the client to be used to communicate with it. As part of https://github.com/eea-oasis/baseline/issues/483, you can then implement the client with these basic functionalities setup (i.e. migrations, CRUD patterns...) and every dev will implement the necessary migrations for the scope of the issue he\she is working on." -Ogjnen

**Comment by ognjenkurtic** [comment]
Hey @Ybittan , this one might be interesting for us https://typeorm.io/
