### ISSUE TITLE
SRI Storage Component - SQL Calls to DB

### ISSUE THREAD

**Issue by Ybittan** [eea-oasis/baseline#483]
## Overview

Would like to create SQL calls in Typescript that would allow the monolith to access and interact with the Postgres DB. 

### Reference

- [Database prep issue](https://github.com/eea-oasis/baseline/issues/482)
- [SRI Storage](https://github.com/eea-oasis/baseline/issues/478)

### Assumptions

- This issue assumes DB prep issue is completed. 

### Acceptance

- Enable the repo to make SQL calls to the Postgres DB
- Test this technology to ensure accuracy

## Tasks

- [x] Setup Node.js and node-postgres in the repo
- [x] Implement necessary functions to allow other components to make calls to the DB
- [x] Send queries to DB running in a docker container
- [ ] Create tests to make sure calls are returning and sending the right information
- [ ] Implement an ORM

**Comment by Ybittan** [comment]
Updated based on suggestions from a comment, reference below:

"I do not think you should and could map all the necessary data at this point.For the purpose of issue #482, i think it is enough to map the general requirements from the storage layer (as you already did bellow), and then decide on the storage tech itself as well as the client to be used to communicate with it. As part of #483, you can then implement the client with these basic functionalities setup (i.e. migrations, CRUD patterns...) and every dev will implement the necessary migrations for the scope of the issue he\she is working on." -Ogjnen

**Comment by ognjenkurtic** [comment]
Hey @Ybittan, this one might be interesting https://typeorm.io/

**Comment by Therecanbeonlyone1969** [comment]
@ognjenkurtic @Ybittan  ... FYI as to typeORM 
- https://news.ycombinator.com/item?id=26888369#:~:text=js%20and%20TypeScript-,TypeORM%20is%20poorly%20maintained%20(the%20lead%20author%20had%20a%20breakdown,it's%20usage%20clunky%20and%20dangerous.
- https://www.slant.co/options/20606/~typeorm-review
- https://betterprogramming.pub/prisma-vs-typeorm-60d02f9dac64

**Comment by ognjenkurtic** [comment]
As agreed on the call @Ybittan , i ll continue on this task to research Prisma vs Sequelize and implement the lib that fits us better.
