### ISSUE TITLE
SRI Workgroup Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#485]
## Overview

Create SRI Workgroup Component in the typescript language utilizing the Workgroup Component Requirements document as an outline of said component’s functionalities and structure.

### Reference

- [Workgroup Component Requirements document](https://docs.google.com/document/d/10LWXIBPjzEUrRMfMgeua6_ufiAcmEl6QRRhRLC301Dg/edit?usp=sharing)

### Assumptions

- A portion of necessitated componential APIs, functionalities, and structures likely lay undocumented/undiscovered
- Cross-component integration is not considered within the scope of this issue

### Acceptance

- Implement Workgroup Component Interface 
- Implement Workgroup Component class inheriting interface 
- Implement Workgroup Component CRUD API
- Implement Workgroup Component functions 
- Implement Unit tests assessing Workgroup Component above implementations

## Tasks

- [x] Implement Workgroup Component Interface 
- [x] Implement Workgroup Component class inheriting interface 
- [x] Implement Workgroup Component CRUD API
- [x] Implement Workgroup Component functions 
- [x] Implement Unit tests assessing Workgroup Component above implementations
