### ISSUE TITLE
SRI Workflow Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#486]
## Overview

Create SRI Workflow Component in the typescript language utilizing the Workflow Component Requirements document as an outline of said component’s functionalities and structure.

### Reference

- [Workflow Component Requirements document](https://docs.google.com/document/d/1GRsZrS-OZNU_PEnmzluSChYw85LW0tBlECJwCZcooFk/edit?usp=sharing)

### Assumptions

- A portion of necessitated componential APIs, functionalities, and structures likely lay undocumented/undiscovered
- Cross-component integration is not considered within the scope of this issue

### Acceptance

- Implement Workflow Component Interface 
- Implement Workflow Component class inheriting interface
- Implement Workflow CRUD API
- Implement Workflow Component functions 
- Implement Unit tests assessing Workflow Component above implementations

## Tasks

- [x] Implement Workflow Component Interface 
- [x] Implement Workflow Component class inheriting interface
- [x] Implement Workflow CRUD API
- [x] Implement Workflow Component functions 
- [x] Implement Unit tests assessing Workflow Component above implementations
