### ISSUE TITLE
SRI Workstep Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#487]
## Overview

Create SRI Workstep Component in the typescript language utilizing the Workstep Component Requirements document as an outline of said component’s functionalities and structure.

### Reference

- [Workstep Component Requirements document](https://docs.google.com/document/d/1jl18QixqTEH30jrdlW0dD-DOydMX1L8lEGCucKv3SXs/edit?usp=sharing)

### Assumptions

- A portion of necessitated componential APIs, functionalities, and structures likely lay undocumented/undiscovered
- Cross-component integration is not considered within the scope of this issue

### Acceptance

- Implement Workstep Component Interface 
- Implement Workstep Component class inheriting interface 
- Implement Workstep Component CRUD API
## Tasks

- [x] Implement Workstep Component Interface 
- [x] Implement Workstep Component class inheriting interface 
- [x] Implement Workstep Component CRUD API
