### ISSUE TITLE
SRI Subjects Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#488]
## Overview

Create SRI Subject Component in the typescript language utilizing the Subjects and Accounts Component Requirements document as an outline of said component’s functionalities and structure.

### Reference

- [Reference](https://docs.google.com/document/d/1DCi0Ap9EK2cBxxEVzmOPkdkcl1hnv7-qoELGHODb1PM/edit)

Assumptions
- A portion of necessitated componential APIs, functionalities, and structures likely lay undocumented/undiscovered
- Cross-component integration is not considered within the scope of this issue

### Acceptance

 - Subject Component Interface created according to preparation document specification
 - Subject Component class inheriting interface created according to preparation document specification
 - Subject Component associated minor objects, model interfaces, and classes created as adhering to the preparation document specification
 - Subject Component associated utilities and functions created as adhering to guidelines inherently established through preparation document specification
 - Unit tests assessing Subject Component functionality, structure and instantiation created as covering at least 80% of viable code

## Tasks

- [x] Implement BPI Subject model  through interface and class that implements it
- [ ] Implement BPI Subject CRUD API (without talking to storage atm)
- [ ] Implement tests for above functionalities
