### ISSUE TITLE
SRI Zero-Knowledge Component: IPFS preparation tasks

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#497]
## Overview

Setup IPFS for the storage of the Sparse Merkle tree.

### Reference

- [Documentation](https://docs.google.com/document/d/1FTcW1kPa-75AqaYLdlPeL2TXNR-NJy_nN1ZUvgk-m18/edit?usp=sharing)
- [Library to be used](https://js.ipfs.tech)

### Assumptions

- The IPFS will be a private instance used to share data between the participants of the workgroup.

### Acceptance

- Can store and retrieve data from the IPFS

## Tasks

- [ ] Install IPFS implementation for node.js 
- [ ] Adding data to IPFS
- [ ] Retrieving data from IPFS

**Comment by Therecanbeonlyone1969** [comment]
something to consider -> there are significant advantages to using IPFS cluster library e.g. redundancy, MFS, and performance. However, this is only available in go, and is not compatible with the js library (speaking from personal experience). 

So:

1. If we only want to use one langauge throughout the stack AND we want to be able to use IPFS cluster, we would have to write everything in go. 
2. If we are sure that we will not use IPFS cluster then js is ok, and we can stick with ts throughout the stack
3. if we want to allow for mxing then we can do ts and use the ipfs cluster library

What are people's thoughts?

Or should we use a different storage solution in append-only mode e.g. Mongo or Postgres or Couch?

**Comment by Manik-Jain** [comment]
I agree with @Therecanbeonlyone1969 
Or may be, we can have most of code base in TS, and using Kafka or normal axios call to a dedicated Go package that interacts with IPFS cluster for the merkle tree storage.
