### ISSUE TITLE
SRI Zero-Knowledge Component: Zero-Knowledge Circuit Provider

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#499]
## Overview

Implement a zero-knowledge circuit to proof that a Merkle root exists as a leaf in a given Sparse Merkle Tree

### Reference

- [Documentation](https://docs.google.com/document/d/1FTcW1kPa-75AqaYLdlPeL2TXNR-NJy_nN1ZUvgk-m18/edit?usp=sharing)
- [References](https://docs.gnark.consensys.net/en/latest/)

### Assumptions

- Snark is being used for the Zero-Knowledge Proof.

### Acceptance

- Create a proof using the given circuit
- Verify the proof

## Tasks

- [ ] Implement the ZKP circuit
- [ ] Generate proof using the created circuit
- [ ] Verify the proof

**Comment by Therecanbeonlyone1969** [comment]
Questions:
- which types of ZKP will the SRI support?
- which prover system(s) will the SRI support?
- will we support private trusted set-up generation or only either rely on public trusted set-ups or prover systems not requiring a trusted set-up?
- will we support recursive proofs? If so to what depths?
- what curves, especially for signatures will we support -> in other words do we care about performance at all or not?
- based on the above which libraries will we support, and if only one to begin with, which one?

Let's discuss on a series of dedicated calls
