### ISSUE TITLE
SRI Zero-Knowledge Component: Integration

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#500]
## Overview

Integrate all the ZK components (Merkle tree, Sparse Merkle Tree and Zero-Knowledge Circuit).

### Reference

- [Documentation](https://docs.google.com/document/d/1FTcW1kPa-75AqaYLdlPeL2TXNR-NJy_nN1ZUvgk-m18/edit?usp=sharing)

### Acceptance

- Workflow participants are able to create a Merkle tree from their documents
- Workflow participants are able to access the sparse Merkle tree
- Workflow participants are able to use the zk circuit to verify that the root of their Merkle tree exists as a leaf in the shared Sparse Merkle tree

## Tasks

- [ ] Use the Merkle Tree component to generate a Merkle Tree from user document and retrieve the root (R).
- [ ] Insert the root R into the Sparse Merkle Tree (S) as a leaf
- [ ] Send a message to all Workflow participants that a leaf has been added to the Sparse Merkle Tree
- [ ] Generate a ZK Proof that R is a leaf in S

**Comment by Therecanbeonlyone1969** [comment]
See my comments on #499 #498 #497, this cannot be decided in silos but rather together as a cohesive framework(s).

Thoughts?
