### ISSUE TITLE
SRI Transactions - Model and CRUD Api

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#532]
## Overview

Create SRI Transaction model and CRUD APi in the typescript language utilizing the Subjects and Accounts Component Requirements document as an outline of said component’s functionalities and structure.

### Reference

- [Reference](https://docs.google.com/document/d/1Bn9Bn0E9MZ1u6kLi7LYcQUdiczvGg9r-XEmOqetuclY/edit)

Assumptions
- A portion of necessitated componential APIs, functionalities, and structures likely lay undocumented/undiscovered
- Cross-component integration is not considered within the scope of this issue

### Acceptance

 - Transaction model created according to preparation document specification
 - Transaction CRUD API implemented according to preparation document specification 
 - Unit tests assessing Transaction CRUD API functionality, structure and instantiation created as covering at least 80% of viable code

## Tasks

- [x] Implement BPI Transaction model 
- [x] Implement BPI Transaction CRUD API
- [x] Implement tests for above functionalities
