### ISSUE TITLE
SRI Subject Account Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#540]
## Overview

Integrate with BPI Account and BPI Subject

### Reference

Check issue https://github.com/eea-oasis/baseline/issues/489 for more context

## Tasks

- [x] Implement BPI Subject Account model through interface and class that implements it
- [x] Implement BPI Subject Account CRUD
- [x] Implement BPI Subject Account tests
