### ISSUE TITLE
SRI Zero-Knowledge Component: CCSMAnchorHash Contract

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#545]
## Overview

Deploy a CCSMAnchorHash contract on the blockchain to store and retrieve the content-addressable hash of the participant's documents.

### Reference

- [Documentation](https://docs.google.com/document/d/1C5QSz9j3Ur-5HT2yqswsQv5YNEhi9jE3/edit?usp=sharing&ouid=103115181691928596573&rtpof=true&sd=true) : Refer to the "ZK Component" section

### Assumptions

- The current iteration will focus on state synchronization. Future iterations will add privacy using zero-knowledge circuits.

### Acceptance

- Store the content addressable hash of a document
- Verify the existence of the content addressable hash

## Tasks

- [ ] Initialise a map within a solidity contract
- [ ] Add items to map
- [ ] Verify items exists in the map

**Comment by Therecanbeonlyone1969** [comment]
@biscuitdey please take a look at https://github.com/0xpolygonhermez and comment ... using a zkEVM as BRI-3s execution framework and CCSM anchor mechanism might significantly simplify our deployment architecture since we then only have to wrap the zkEVM with the Baseline specific methods and connect the Ethereum accounts to BPI Accounts and workflows and worksteps to smart contracts (workflow) and smart contract functions (worksteps) cc @Kasshern @ognjenkurtic @skosito @Manik-Jain @Ybittan

**Comment by biscuitdey** [comment]
Closing issue because it relates to post current discussion on the SRI. Will reopen later if required.
