### ISSUE TITLE
SRI Messaging Component- Interfaces, Classes and API

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#551]
## Overview

Implement a basic model and CRUD API for messaging, based on the document from the referenced issue.

### Reference

#514 

### Acceptance

 - Messages can be read, created, updated and deleted using the API
 - All unit tests past
 
## Tasks

- [] Implement BPI Message model through interface and class that implements it
- [] Implement BPI Message CRUD
- [] Implement BPI Message tests
