### ISSUE TITLE
[SRI] ZKP Component: Add BPI Account to Anchor Hash

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#597]
## Overview

Add BPI Account as a parameter to CCSMAnchorHash model. It will signify the agreement state on which the current state change (as denoted by the current CCSMAnchorHash) has been applied.

### Reference

- Zero-knowledge Interations document: [Anchor Hash DTO](https://docs.google.com/document/d/1mkO5oou0TWk6kVHbTB01dyj7wuNGTfR9w6PAxSgXdGI/edit#bookmark=id.edbohxp41gnc)

### Assumptions

- During audit, BPI Account might be required to identify the agreement state on which state change was applied.

### Acceptance

- BPI Account needs to be included in the CRUD operations of CCSMAnchorHash

## Tasks

- [ ] Add BPI Account to CCSMAnchorHash DTO and model
- [ ] Add BPI Account to CreateCCSMAnchorHash command handler.
- [ ] Add BPI Account to VerifyCCSMAnchorHash command handler.

**Comment by biscuitdey** [comment]
Closing issue because it relates to post current discussion on the SRI. Will reopen later if required.
