### ISSUE TITLE
[SRI] ZKP Component: Implement zk circuit

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#600]
## Overview

The merkle proof (that the content-addressable hash is part of the state history merkle tree) is wrapped in a ZK proof with the content addressable hash as the public input.

### Reference

- Zero-knowledge interactions: [Wrap Merkle proof](https://docs.google.com/document/d/1mkO5oou0TWk6kVHbTB01dyj7wuNGTfR9w6PAxSgXdGI/edit#bookmark=id.1kpvfjz17ywa)

### Acceptance

- ZK proof can be verified by any third-party.

## Tasks

- [ ] Generate merkle proof
- [ ] Generate zk circuit with merkle proof, merkle tree and leaf
- [ ] Generate zk proof and witness
- [ ] Verify the zk proof

**Comment by biscuitdey** [comment]
As the gnark library is written in go, options for converting go to typescript -> 

1. https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf
2. https://www.npmjs.com/package/node-go-require 
3. https://www.npmjs.com/package/@types/ffi

**Comment by biscuitdey** [comment]
Closing issue because it relates to post current discussion on the SRI. Will reopen later if required.
