### ISSUE TITLE
[SRI] Merkle Tree CRUD

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#601]
## Overview

Add service for CRUD of merkle tree. Merkle tree will be used to store the state history.

### Reference

- Zero-knowledge interactions: [State History](https://docs.google.com/document/d/1mkO5oou0TWk6kVHbTB01dyj7wuNGTfR9w6PAxSgXdGI/edit#bookmark=kix.6ggmhvi36umn)

### Acceptance

- CRUD merkle tree

## Tasks

- [x] CRUD of merkle tree
- [x] Add leaves to merkle tree
- [x] Generate merkle proof (no longer applicable)
- [x] Verify merkle proof (no longer applicable)
- [x] Remove all external routes (merkle controller and command / query handler)
