### ISSUE TITLE
[SRI] ZKP Component: Generate Content Addressable Hash

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#602]
## Overview

CRUD management of Content Addressable Hash. Referred to as the CCSMAnchorHash, SHA256() of postgresql is used to generate it.

### Reference

- [Content Addressable Hash](https://docs.google.com/document/d/1mkO5oou0TWk6kVHbTB01dyj7wuNGTfR9w6PAxSgXdGI/edit#bookmark=id.d5j0ngcxat5t)
- [Hash Index](https://www.postgresql.org/docs/current/indexes-types.html)

### Acceptance

- Returns corresponding document of a content-addressable hash

## Tasks

- [x] Create Postgres table (with hash index) to store content-addressable hash
- [x] Generate a content-addressable hash
- [x] Retrieve corresponding document of a content-addressable hash
