### ISSUE TITLE
[SRI] Workgroup Setup Functionality

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline#604]
## Overview

Create SRI Workgroup Setup Functionality within the BRI-3 project utilizing the Workgroup Setup Proposal document as a guide

### Reference

- [Workgroup Setup Proposal ](https://docs.google.com/document/d/1pV9yOIRKfj9uBobKh1s2KZI44gfmWOEDr1_wTqtxPZk/edit?usp=sharing)

### Assumptions

- Authentication, Authorization, Workgroup Invitation, and any other code necessary to fully complete this functionality, but is not included within the scope of this issue will be commented as TODO

### Acceptance

- Alter CreateWorkgroup method in accordance with available auth
- Implement creator as administrator and participant 
- Implement default starting privacy and security policies
- Assumes initial state between participants
- Implement Unit tests assessing Workgroup Component above implementations

## Tasks

- [x] Alter CreateWorkgroup method to default add creator as admin and participant
- [x] Alter default sec and priv policies in accordance with new sec and priv policies
- [x] Implement Unit tests assessing Workgroup Setup functionality
