### ISSUE TITLE
[SRI] Simple RBAC approach

### ISSUE THREAD

**Issue by skosito** [eea-oasis/baseline#616]
## Overview

Document where we are discussing this: https://docs.google.com/document/d/1Gl1jxRTdGMOBSqb7bexC2znHIhd2a7WzJBMsT_rvDi4/edit

No matter what we decide in terms of set of roles or permission, we would need to implement it in nest js. Purpose of this task is to implement RBAC handling using this guide https://docs.nestjs.com/security/authorization and to decide if using nestjs guards is enough or we need to introduce casl library mentioned in article for more granular permissions.

It is probably best to start with simplest RBAC with this issue, and add one or two roles and use it on one endpoint for illustration, perhaps internal/external bpi subject roles. We have an option to store role info in jwt or to fetch it in every request, which should be implementation detail depending on option that nestjs approaches work best with.

### Reference

Doc: https://docs.google.com/document/d/1Gl1jxRTdGMOBSqb7bexC2znHIhd2a7WzJBMsT_rvDi4/edit
NestJs tutorial: https://docs.nestjs.com/security/authorization
Casl: https://casl.js.org/v5/en/guide/install
Do it in 7 minutes video :) : https://www.youtube.com/watch?v=xd3LJqdU1ig&ab_channel=Auth0

### Questions

None regarding this particular issue, but still some open questions in the doc, which would result in more issues.

### Assumptions

Only assumption is making it simple but as extensible as possible.

### Acceptance

One or two roles, used to authorize user on one endpoint.

## Tasks

- [x] Add roles info to db
- [x] Store roles in jwt or fetch it from db on every request depending on simplicity and nestjs
- [x] Protect endpoint with this
- [x] Tests changes if applicable
- [x] Present to the team
