### ISSUE TITLE
[SRI] CRUD for State Object

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#629]
## Overview

CRUD for the State Object as defined by the standard.

### Reference

- [Standard](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#22-state-object)

### Acceptance

- CRUD tasks can be performed for State Object

## Tasks

- [ ] Implement State Object model
- [ ] Implement CRUD for the State Object model
- [ ] Implement tests for above functionalities

**Comment by ognjenkurtic** [comment]
As agreed on the core devs call from today, we ll implement this as part of [this](https://github.com/eea-oasis/baseline/issues/702) issue and potential subsequent ones.
