### ISSUE TITLE
[SRI] Write a happy case E2E test

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#633]
## Overview

This test should trigger endpoints to login as internal BPI Subject, create two Bpi Subjects, create a workgroup and add the Bpi Subjects to it and then verify the state by triggering GET endpoints.

### Reference

n/a

### Questions

n/a

### Assumptions

- This test serves as a basis so that we can start expanding and writing tests for more complex functionalities that are coming (messagging, state changes ...) 
- 
### Acceptance

- Mentioned E2E test can be run by a single script
- Executed on every commit to main after the unit tests 

## Tasks

- [x] Implement the test
- [x] Add run instructions to readme
- [ ] Add to Github actions

**Comment by ognjenkurtic** [comment]
We ll do github action in milestone 5
