### ISSUE TITLE
[SRI] Produce a POC of a separate service hosted next to a BPI instance hosting ZK circuits that can be executed by the BPI

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#670]
## Overview

Based on the discussion in the SRI use-case doc, we agreed that we ll support generic business cases by creating a separate service that will host precompiled circuits and that will be hosted next to the BPI instance. Scope of this story is to do a simple POC of that service, a docker hosted service that can receive inputs by listening on localhost and produce back the output of a circuit execution in a JSON format.

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit?disco=AAAAt0irQX8)

### Assumptions

- THe admin of the BPI is in charge of deploying this service and making it available to the BPI.
- THe BPI would trigger a circuit available from this service via a HTTP call in the docker network.

### Acceptance

- Service runs standalone in a docker container and listens on a configurable port
- Spits out a JSON output of a dummy circuit when called by the BPI

## Tasks

- [ ] Research most appropriate lang to write this
- [ ] Write with a dummy circuit 
- [ ] Dockerize
- [ ] Document triggering via CURL

**Comment by biscuitdey** [comment]
Here is a [link](https://blog.celer.network/2023/03/01/the-pantheon-of-zero-knowledge-proof-development-frameworks/) for comparing performances of gnark and snarkjs libraries. To summarise, 

- Proof generation time: For Groth16, gnark is 5~10 times faster than snarkjs
- Peak memory usage: It is comparable for both libraries.
- CPU utilisation: Gnark shows better CPU utilisation.

As discussed during call on 27/04/2023, snarkjs is preferred due to its ease of development (a separate service for running zk-circuits in golang is not required). Also, It is deemed sufficient for our use case based on the number of constraints in our circuit.

Keeping the above-mentioned points in mind, I will go ahead with developing circuits using snarkjs. The module interface will allow for using other libraries interchangeably.

**Comment by ognjenkurtic** [comment]
Closing as we agreed to take the approach of snarkjs as explained in comment  above
