### ISSUE TITLE
[SRI] Update BpiAccount state after successful execution of the workstep

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#702]
## Overview

Based on the description from the SRI use-case doc, we want to store outputs of the workstep execution in the shared BpiAccount state. Scope of this one is to agree on the final structure we want to use and then implement storage. 

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)
- [State object Model proposal](https://docs.google.com/document/d/1sitzsboY3oUzjG5SoweLDvTiiQ4A-yLUEOTqdu1U8q8/edit)

### Questions

- We need to agree on #698, #699, #700, #701 before this one can be picked up.

### Tasks to complete

- [ ] Store state tree on DB (materialized path)

Add the following items to the executeTransaction function in transaction.agent.ts

- [x] Translate tx.payload and current bpi account state into appropriate circuit inputs
- [x] Hash(root of the merkelized invoice + Hash (witness))
- [x] Store the hash as the leaf on state tree

**Comment by ognjenkurtic** [comment]
@biscuitdey Do you have any questions or comments related to this one, based on our discussion from the last sync meeting? I am now starting to go through the proposed approach from the linked docs to try to finalize the issue description and acceptance criteria.

**Comment by ognjenkurtic** [comment]
SRI use-case doc proposal:

> DB storage of the BPI Account looks like this:
> 
> 1. stateTree

MerkeTree where a leaf is the root hash of the combination of the root of the merkelized invoice and the hash of the witness, both being part of the output of the executed workstep. 

> 2. historyTree

MerkeTree where each leaf is a root of the state tree, with history tree root being recalculated each time.

> 3. Merkelized payload (Invoice)

Latest state of the payload which is being synchronized (an invoice), merkelized

> 4. Witness

Latest witness as produced by the executed circuit


Open question:

Do we need to keep track (store) points 3 and 4 for every workstep execution or just latest one?

**Comment by ognjenkurtic** [comment]
[Here](https://makandracards.com/makandra/45275-storing-trees-in-databases) is a good overview of patterns that can be used to store a merkle tree in a relational database. Option 2: Materialized Path sounds like something we could utilize unless we decide to go with a JSON blob approach.

**Comment by Ybittan** [comment]
Core Dev Call 8/21: Agree to implement Option 2: Materialized Path in above doc. Storage issue to be split into several to be worked on in parallel

**Comment by ognjenkurtic** [comment]
For state tree, we agreed to take the root of the merkelized invoice and the witness, concatenate them, hash them and store the hash as the leaf.

Since we ll be using Materialized path pattern to store the merke tree in the DB, we ll have a separate table to store both the merkelized payload and the witness as a single entry referencing the concrete leaf entry of that tree.

**Comment by ognjenkurtic** [comment]
Work on the POC can be tracked here: feat/bpi_account_storage_prisma_poc

**Comment by biscuitdey** [comment]
@Therecanbeonlyone1969 

Question:
StateTree: (merkelizedInvoice root + witness)

In the circuit (i.e. during witness creation), we are checking for non-inclusion merkle proof of only the merkelizedInvoice root in the state tree. Which will always fail as the stateTree leaf is (merkelizedInvoice root + witness), and NOT ((merkelizedInvoice root).

What should we be checking for non-inclusion inside the circuit?

**Comment by biscuitdey** [comment]
As per discussions on slack, removing the non-inclusion merkle proof from the circuit.

Conflict : 
StateTree: (merkelizedInvoice root + witness)
In the circuit (i.e. during witness creation), we are checking for non-inclusion merkle proof of only the merkelizedInvoice root in the state tree. Which will always fail as the stateTree leaf is (merkelizedInvoice root + witness), and NOT ((merkelizedInvoice root).
What should we be checking for non-inclusion inside the circuit?

After exploring various options, Andreas confirmed that non-inclusion proof is actually not required and "as long as the state is finalized by the workgroup participants, then the trxn payload only needs a zro-knowledge proof of correct execution of the state transition that is it"
