### ISSUE TITLE
Implement circuit from Workstep 2 from the SRI use-case docs

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#727]
## Overview

Based on the description from the SRI use-case doc, we want to execute a circuit as part of workstep 2execution that will verify that the rules related to invoice exchange have been followed. Scope of this story is to implement the simple version of this circuit with the following rules:

Invoice status must transit from NEW to VERIFIED.. 
BuyerInvoiceID must be provided. 
All other fields must remain the same.
Signature of the buyer is present and valid.

Circuit inputs would be:

invoice status. 
root of the tree of the merkelized invoice, 
state tree,
signature of the buyer

Circuit output is a witness whose storage and handling will be tackled as part of a separate story.

This circuit should be implemented as a separate file inside of the ...\zeroKnowledgeProof/services/circuit/snarkjs/workstep2.circom.

Once implemeted, aslo implement circuit inputs preparation and executiion in the same manner it is done for workstep 1.

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)

### Tasks

- [x] Implement the circuit
- [x] Implement circuit inputs preparation
- [x] Implement circuit execution

**Comment by biscuitdey** [comment]
@Therecanbeonlyone1969 Just verifying again. The workstep 2 circuit will contain the following constraints:

- Status == VERIFIED
- Inclusion proof (Merklelized invoice part of state tree)
- Signature of buyer is valid
