### ISSUE TITLE
Implement circuit from Workstep 3 from the SRI use-case docs

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#728]
## Overview

Based on the description from the SRI use-case doc, we want to execute a circuit as part of workstep 3 execution that will verify that the rules related to invoice exchange have been followed. Scope of this story is to implement the simple version of this circuit with the following rules:

Invoice status must transit from VERIFIED to PAID. 
All other fields must remain the same.
Signature of the buyer is present and valid.

Circuit inputs would be:

invoice status. 
root of the tree of the merkelized invoice, 
state tree,
signature of the buyer

Circuit output is a witness whose storage and handling will be tackled as part of a separate story.

This circuit should be implemented as a separate file inside of the ...\zeroKnowledgeProof/services/circuit/snarkjs/workstep2.circom.

Once implemeted, aslo implement circuit inputs preparation and executiion in the same manner it is done for workstep 1.

### Reference

- [SRI use-case doc](https://docs.google.com/document/d/14W2Pr00K8SBPPO7-aQiDP73uMAEwd6rwK7Tvtvfxeng/edit)

### Tasks

- [ ] Implement the circuit
- [ ] Implement circuit inputs preparation
- [ ] Implement circuit execution

**Comment by biscuitdey** [comment]
Completed
