### ISSUE TITLE
SRI - Research way to allow SRI to support general use-cases for state synhronization

### ISSUE THREAD

**Issue by ognjenkurtic** [eea-oasis/baseline#744]
## Overview

SRI supports a single use-case - exchanging invoice data between counterparties that follow a strict set of business rules. For milestone 5, we want to offer support for any kind of use-case. Scope of this issue is to create a design proposal that would serve as a basis for implementation during milestone 5.

### Questions

- Could we allow worktroup participants to provide their own precompiled circuits that are then attached to worksteps using the mechanism we have in place? How would be handle circuit inputs preparation in that case?
- Could we provide circuit building blocks (i.e equality, less than, sig verification) that can be used to construct more complex business rules?
- Other options

### Acceptance

- Documented design proposal after a broad discussion with the team

## Tasks

- [x] Prepare doc for discussion
- [x] Organize team discussions
- [x] Draft a shared proposal
- [x] Open implementation issues

**Comment by ognjenkurtic** [comment]
Agreement is to go with the approach where we use JSON schema to translate transaction payloads into circuit inputs. These schema objects would be uploaded as an artifact by the workgroup admin or participants.

**Comment by ognjenkurtic** [comment]
@Therecanbeonlyone1969 please share a doc with the initial proposal and link here.

**Comment by ognjenkurtic** [comment]
@Therecanbeonlyone1969 @Kasshern  @biscuitdey @Ybittan  here is a start: https://docs.google.com/document/d/1AzyUK0OMATe0XRPaTbayRR3KmuaFLMAKybIytaVVBdY/edit

**Comment by ognjenkurtic** [comment]
First issue created - https://github.com/eea-oasis/baseline/issues/766
Others to follow

**Comment by ognjenkurtic** [comment]
https://github.com/eea-oasis/baseline/issues/776
https://github.com/eea-oasis/baseline/issues/777
