### ISSUE TITLE
SRI - Update Circom Circuit to use Eddsa Signature verification

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline#758]
## Overview

Previously we accepted only Ecdsa signatures in the SRI because we used Metamask to login and Metamask used Ecdsa signatures. But Ecdsa signature verification inside circom zk circuits is very [inefficient](https://github.com/eea-oasis/baseline/pull/752) & the available alternatives are not widely used (causing issues with [interoperability](https://github.com/eea-oasis/baseline/pull/752#issuecomment-1733898957)). Keeping these issues in mind, SRI team has decided to use Eddsa signatures.

### Reference

PR #752

## Tasks

- [ ] Remove Ecdsa sig verifier
- [ ] Add Eddsa sig verifier to circom circuit
- [ ] Prepare circuit inputs to accept Eddsa signature

**Comment by biscuitdey** [comment]
@Therecanbeonlyone1969  Is there any library you recommend for generating Eddsa signatures? I found the following libraries :

1. [@transmute/ed25519-signature-2018](https://www.npmjs.com/package/@transmute/ed25519-signature-2018)
2. [@digitalcredentials/ed25519-signature-2020](https://www.npmjs.com/package/@digitalcredentials/ed25519-signature-2020)
3. [@digitalbazaar/ed25519-signature-2020](https://www.npmjs.com/package/@digitalbazaar/ed25519-signature-2020)

**Comment by Therecanbeonlyone1969** [comment]
@biscuitdey here you go https://github.com/paulmillr/noble-curves

**Comment by Therecanbeonlyone1969** [comment]
@biscuitdey also circomlibjs supports EdDSA sigs such as with MimC e.g.

```
const buildEddsa = require("circomlibjs").buildEddsa;
import * as crypto from "crypto";

const SNARK_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const genRandomBabyJubValue = () => {
  // Prevent modulo bias
  //const lim = BigInt('0x10000000000000000000000000000000000000000000000000000000000000000')
  //const min = (lim - SNARK_FIELD_SIZE) % SNARK_FIELD_SIZE
  const min = BigInt("6350874878119819312338956282401532410528162663560392320966563075034087161851");

  let rand;
  // eslint-disable-next-line no-constant-condition
  while (true) {
    rand = BigInt("0x" + crypto.randomBytes(32).toString("hex"));

    if (rand >= min) {
      break;
    }
  }

  const privKey = rand % SNARK_SCALAR_FIELD;

  return privKey;
};

async function eddsasig() {
    const eddsa = await buildEddsa();
    const plaintext = rand = BigInt("0x" + crypto.randomBytes(32).toString("hex"));
    const F = eddsa.F;
    const issuerPrivKey = genRandomBabyJubValue();
    const issuerPubKey = eddsa.prv2pub(issuerPrivKey.toString());
    const signature = eddsa.signMiMC(issuerPrivKey.toString(), F.e(plaintext));

    return signature;
    }
```

**Comment by biscuitdey** [comment]
@Therecanbeonlyone1969 

> @biscuitdey also circomlibjs supports EdDSA sigs such as with MimC e.g.
> 
> ```
> const buildEddsa = require("circomlibjs").buildEddsa;
> import * as crypto from "crypto";
> 
> const SNARK_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
> const genRandomBabyJubValue = () => {
>   // Prevent modulo bias
>   //const lim = BigInt('0x10000000000000000000000000000000000000000000000000000000000000000')
>   //const min = (lim - SNARK_FIELD_SIZE) % SNARK_FIELD_SIZE
>   const min = BigInt("6350874878119819312338956282401532410528162663560392320966563075034087161851");
> 
>   let rand;
>   // eslint-disable-next-line no-constant-condition
>   while (true) {
>     rand = BigInt("0x" + crypto.randomBytes(32).toString("hex"));
> 
>     if (rand >= min) {
>       break;
>     }
>   }
> 
>   const privKey = rand % SNARK_SCALAR_FIELD;
> 
>   return privKey;
> };
> 
> async function eddsasig() {
>     const eddsa = await buildEddsa();
>     const plaintext = rand = BigInt("0x" + crypto.randomBytes(32).toString("hex"));
>     const F = eddsa.F;
>     const issuerPrivKey = genRandomBabyJubValue();
>     const issuerPubKey = eddsa.prv2pub(issuerPrivKey.toString());
>     const signature = eddsa.signMiMC(issuerPrivKey.toString(), F.e(plaintext));
> 
>     return signature;
>     }
> ```

I am using this same library

**Comment by ognjenkurtic** [comment]
Currently blocked by https://github.com/eea-oasis/baseline/issues/765
